# grant.yaml
---
# 1. Member 서비스가 Web-Proxy에게 권한 부여
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-web-proxy
  namespace: member-service
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: web-proxy
  to:
  - group: ""
    kind: Service

---
# 2. Board 서비스가 Web-Proxy에게 권한 부여
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-web-proxy
  namespace: board-service
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: web-proxy
  to:
  - group: ""
    kind: Service
