apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: web-proxy
  labels:
    app: frontend-proxy
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        sendfile        on;
        keepalive_timeout  65;

        # (1) 회원 서비스 (기본)
        upstream member_backend {
            server tomcat-member-service.member-service.svc.cluster.local:8080;
        }

        # (2) 게시판 서비스
        upstream board_backend {
            server tomcat-board-service.board-service.svc.cluster.local:8080;
        }

        server {
            listen 80;
            server_name  localhost;

            location /board.do {
                proxy_pass          http://board_backend;
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto $scheme;
            }

            location / {
                proxy_pass          http://member_backend;
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto $scheme;
            }
        }
    }
